package interfacegrafica;

//import lists
import java.util.ArrayList;
import java.util.List;

//import icons
import javax.swing.Icon;
import javax.swing.ImageIcon;

//import GUI utilities
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.SwingUtilities;

import bdconnection.BDConnection;
import java.sql.SQLException;

/**
 *
 * @author Eldoardo
 */
public class Main extends javax.swing.JFrame {
    BDConnection bd;
    //Objeto localizador para abrir a tela de criação de listas    
    JFrame frame = (JFrame)SwingUtilities.getWindowAncestor(this);
    
    //Arrays de labels (criacao dinamica)
    List<JLabel> listas = new ArrayList<>();
    List<JLabel> cartasBd = new ArrayList<>();
    List<JLabel> cartasLista = new ArrayList<>();
    
//icones
    Icon pasta = new ImageIcon("pasta.png"); 
    Icon deck = new ImageIcon("");
   
    
    /**
     * Creates new form Main
     * @throws java.lang.ClassNotFoundException
     * @throws java.sql.SQLException
     */
    public Main() throws ClassNotFoundException, SQLException {
        initComponents();
        bd =  new BDConnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        create_list = new javax.swing.JButton();
        search_text = new javax.swing.JTextField();
        search_button = new javax.swing.JButton();
        nova_lista = new javax.swing.JLabel();
        nova_lista_nome = new javax.swing.JLabel();
        cardex_text = new javax.swing.JLabel();
        cardex_icon = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setBackground(new java.awt.Color(45, 52, 54));

        create_list.setText("Criar Lista");
        create_list.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                create_listActionPerformed(evt);
            }
        });

        search_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        search_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_buttonActionPerformed(evt);
            }
        });

        nova_lista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nova_listaMouseClicked(evt);
            }
        });

        nova_lista_nome.setFont(new java.awt.Font("Ubuntu Light", 0, 18)); // NOI18N
        nova_lista_nome.setForeground(new java.awt.Color(223, 230, 233));

        cardex_text.setBackground(new java.awt.Color(223, 230, 233));
        cardex_text.setFont(new java.awt.Font("Ubuntu Light", 1, 48)); // NOI18N
        cardex_text.setForeground(new java.awt.Color(223, 230, 233));
        cardex_text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cardex_text.setText("Card Dex");
        cardex_text.setToolTipText("");
        cardex_text.setAlignmentY(0.0F);

        cardex_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfacegrafica/pokeball.png"))); // NOI18N

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(search_text, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(search_button)
                .addGap(18, 18, 18))
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(create_list, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nova_lista_nome, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                            .addComponent(nova_lista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, backgroundLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cardex_icon)
                        .addGap(18, 18, 18)
                        .addComponent(cardex_text)))
                .addContainerGap(675, Short.MAX_VALUE))
            .addComponent(jSeparator1)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(cardex_text))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cardex_icon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(search_text, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search_button, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(nova_lista_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nova_lista, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(create_list, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(141, 141, 141)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(183, 183, 183))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void search_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_buttonActionPerformed

    private void create_listActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_create_listActionPerformed
        //instancia o objeto da tela
        TelaCriaListaModal tclm;
        try {
            tclm = new TelaCriaListaModal(frame, true);
            //mostra a tela
            tclm.setVisible(true);

            // teste para verificar se o form foi preenchido
            if((tclm.tipo != null)&&(tclm.nome != null)){
                JLabel n = new JLabel();
                // caso tenha sido, verifica-se qual o tipo de lista q foi criado
                if("deck".equals(tclm.tipo))    
                    nova_lista.setIcon(pasta);  //caso seja deck : preenche a label com o icon de deck
                else
                    nova_lista.setIcon(pasta);  //se nao: preenche a label com o icon de pasta

                nova_lista_nome.setText(tclm.tipo+": "+tclm.nome); // e por fim damos o nome à nova lista 
            }
        } catch (Exception e) {
            System.out.println(e);
        }
        


    }//GEN-LAST:event_create_listActionPerformed

    private void nova_listaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nova_listaMouseClicked
        //instancia o objeto da tela
        TelaEditaLista tel;
        try {
            tel = new TelaEditaLista(frame, true);
            //mostra a tela
            tel.setVisible(true);
        } catch (Exception e){
            System.out.println(e);
        }
       
    }//GEN-LAST:event_nova_listaMouseClicked

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Main().setVisible(true);
                } catch(Exception e){
                    System.out.println(e);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JLabel cardex_icon;
    private javax.swing.JLabel cardex_text;
    private javax.swing.JButton create_list;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel nova_lista;
    private javax.swing.JLabel nova_lista_nome;
    private javax.swing.JButton search_button;
    private javax.swing.JTextField search_text;
    // End of variables declaration//GEN-END:variables

}
