/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfacegrafica;

import javax.swing.JLabel;

/**
 *
 * @author User
 */
public class TelaEditaLista extends javax.swing.JDialog {
    
    // variavel para alterar o eixo x a cada inserção
    int pos = 6;
    
    /**
     * Creates new form TelaEditaLista
     * @param parent
     * @param modal
     */
    public TelaEditaLista(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        save_list = new javax.swing.JButton();
        search_cards = new javax.swing.JTextField();
        search_button = new javax.swing.JButton();
        filtro_energia = new javax.swing.JLabel();
        filtro_pokemon = new javax.swing.JLabel();
        filtro_treinador = new javax.swing.JLabel();
        add_carta = new javax.swing.JButton();
        return_location = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Editação da lista");

        background.setBackground(new java.awt.Color(225, 225, 225));

        save_list.setText("Salvar");
        save_list.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_listActionPerformed(evt);
            }
        });

        search_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        search_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_buttonActionPerformed(evt);
            }
        });

        filtro_energia.setBackground(new java.awt.Color(225, 112, 85));
        filtro_energia.setForeground(new java.awt.Color(225, 112, 85));
        filtro_energia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        filtro_energia.setText("Energias");
        filtro_energia.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(225, 112, 85), 1, true));

        filtro_pokemon.setBackground(new java.awt.Color(116, 185, 255));
        filtro_pokemon.setForeground(new java.awt.Color(116, 185, 255));
        filtro_pokemon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        filtro_pokemon.setText(" Pokémons");
        filtro_pokemon.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(116, 185, 255), 1, true));

        filtro_treinador.setBackground(new java.awt.Color(253, 203, 110));
        filtro_treinador.setForeground(new java.awt.Color(253, 203, 110));
        filtro_treinador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        filtro_treinador.setText("Treinadores");
        filtro_treinador.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(253, 203, 110), 1, true));

        add_carta.setText("add");
        add_carta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_cartaActionPerformed(evt);
            }
        });

        return_location.setText("jLabel1");
        return_location.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                return_locationMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addContainerGap(176, Short.MAX_VALUE)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                        .addComponent(filtro_pokemon, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(filtro_treinador, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(filtro_energia, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(478, 478, 478)
                        .addComponent(search_cards, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(search_button, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(save_list, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add_carta, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(backgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(return_location, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(filtro_treinador, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(filtro_pokemon, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(filtro_energia, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(search_cards, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(search_button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(269, 269, 269)
                .addComponent(add_carta)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(return_location, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(save_list)
                .addGap(90, 90, 90))
        );

        filtro_energia.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // função de adicionar label
    private void addLabel(){
        pos += 16; // att x da label
        JLabel label = new JLabel(); // instancia nova label
        label.setVisible(true); // torna ela visível
        label.setText("AAAAAAAAAAAAAAAAAA"); // seta o conteúdo
        label.setSize(150,220); // tamanho
        label.setLocation(pos, 422); //localização
        getContentPane().add(label); // colocando o label no frame
        initComponents(); // att frame
    }
    private void save_listActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_listActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_save_listActionPerformed

    private void search_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_buttonActionPerformed

    private void add_cartaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_cartaActionPerformed
        addLabel();
    }//GEN-LAST:event_add_cartaActionPerformed

    private void return_locationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_return_locationMouseClicked

        System.out.println(return_location.getLocation());
    }//GEN-LAST:event_return_locationMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEditaLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEditaLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEditaLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEditaLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaEditaLista dialog = new TelaEditaLista(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_carta;
    private javax.swing.JPanel background;
    private javax.swing.JLabel filtro_energia;
    private javax.swing.JLabel filtro_pokemon;
    private javax.swing.JLabel filtro_treinador;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel return_location;
    private javax.swing.JButton save_list;
    private javax.swing.JButton search_button;
    private javax.swing.JTextField search_cards;
    // End of variables declaration//GEN-END:variables
}
